### ISSUE TITLE
[Bug] 一段时间后的 unobserved 错误会导致直接崩溃

### ISSUE THREAD

**Issue by NanamiArihara** [Rinacm/pixivcs#37]
我局的 unobserved 可以直接**不搭理**

```csharp
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> pixivcs.Util.ResponseErrorException: {"status":"failure","has_error":true,"errors":{"system":{"message":404,"code":null}}}
   at pixivcs.Util.WebAPI.ProcessWebException(WebException ex, Boolean ignored) in E:\VSProjects\repos\temp\pixivcs\pixivcs\Util\WebAPI.cs:line 177
   at pixivcs.Util.WebAPI.Request(String url, Boolean proxyRequired, String postData, Dictionary`2 header, Boolean ignoredException) in E:\VSProjects\repos\temp\pixivcs\pixivcs\Util\WebAPI.cs:line 72
   at pixivcs.Authorization.RequireAuthRequest(String url, String postData, Dictionary`2 header, Boolean ignoredException) in E:\VSProjects\repos\temp\pixivcs\pixivcs\Persistence\Authorization.cs:line 52
   at pixivcs.Util.WebAPI.DownloadJsonWithToken[T](String url, Dictionary`2 header, String postData) in E:\VSProjects\repos\temp\pixivcs\pixivcs\Util\WebAPI.cs:line 46
   at pixivcs.Api.PixivApi.<>c__DisplayClass8_0.<DownloadUploadAsync>b__0(Object token) in E:\VSProjects\repos\temp\pixivcs\pixivcs\Api\PixivApi.cs:line 264
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) pixivcs.Util.ResponseErrorException: {"status":"failure","has_error":true,"errors":{"system":{"message":404,"code":null}}}
   at pixivcs.Util.WebAPI.ProcessWebException(WebException ex, Boolean ignored) in E:\VSProjects\repos\temp\pixivcs\pixivcs\Util\WebAPI.cs:line 177
   at pixivcs.Util.WebAPI.Request(String url, Boolean proxyRequired, String postData, Dictionary`2 header, Boolean ignoredException) in E:\VSProjects\repos\temp\pixivcs\pixivcs\Util\WebAPI.cs:line 72
   at pixivcs.Authorization.RequireAuthRequest(String url, String postData, Dictionary`2 header, Boolean ignoredException) in E:\VSProjects\repos\temp\pixivcs\pixivcs\Persistence\Authorization.cs:line 52
   at pixivcs.Util.WebAPI.DownloadJsonWithToken[T](String url, Dictionary`2 header, String postData) in E:\VSProjects\repos\temp\pixivcs\pixivcs\Util\WebAPI.cs:line 46
   at pixivcs.Api.PixivApi.<>c__DisplayClass8_0.<DownloadUploadAsync>b__0(Object token) in E:\VSProjects\repos\temp\pixivcs\pixivcs\Api\PixivApi.cs:line 264
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---
```

**Comment by Rinacm** [comment]
soudayo

**Comment by Rinacm** [comment]
我已经把TaskScheduler.UnobservedException给删了
